" Display
syntax on
set number relativenumber
set hlsearch
set statusline=%F\ %=%Y\ (%l,%c)
set laststatus=2
set ruler

" Navigation and File Management
set path+=**
set wildmenu

" Tabbing
set softtabstop=4
set tabstop=4
set shiftwidth=4
set autoindent

" use global clipboard
set clipboard=unnamed

" folding

" custom settings for dbt-releases/
au BufNewFile,BufRead */dbt-releases/*.yml set expandtab
au BufNewFile,BufRead */dbt-releases/*.sql set foldmarker=(,)
au BufNewFile,BufRead */dbt-releases/*.sql set foldmethod=marker
au BufNewFile,BufRead */dbt-releases/*.sql set noexpandtab
au BufNewFile,BufRead */dbt-releases/target/* set foldmethod=manual

" custom settings for getaround-analytics/dbt-bq
au BufNewFile,BufRead */getaround-analytics/dbt-bq/*.sql set foldmarker=(,)
au BufNewFile,BufRead */getaround-analytics/dbt-bq/*.sql set foldmethod=marker
au BufNewFile,BufRead */getaround-analytics/dbt-bq/* set expandtab
au BufNewFile,BufRead */getaround-analytics/dbt-bq/target/* set foldmethod=manual

source $HOME/.vim/config/dbt.vimrc
