" Display
syntax on
set number relativenumber
set hlsearch
set statusline=%F\ %=%Y\ (%l,%c)
set laststatus=2
set ruler

" Navigation and File Management
set path+=**
set wildmenu

" Tabbing
set softtabstop=4
set tabstop=4
set shiftwidth=4
set autoindent

" use global clipboard
set clipboard=unnamed

" folding

" custom settings for dbt-pipelines/
autocmd BufNewFile,BufRead */dbt-pipelines/*.sql set foldlevel=0 foldmarker=(,) foldmethod=marker
autocmd BufNewFile,BufRead */dbt-pipelines/*.sql set noexpandtab
autocmd BufNewFile,BufRead */dbt-pipelines/*.sql set nocursorcolumn
autocmd BufNewFile,BufRead */dbt-pipelines/*.yml set cursorcolumn
autocmd BufNewFile,BufRead */dbt-pipelines/*.yml set expandtab
autocmd BufNewFile,BufRead */dbt-pipelines/*.yml set nostartofline
autocmd BufNewFile,BufRead */dbt-pipelines/target/* set foldmethod=manual

" custom settings for getaround-analytics/dbt-bq
autocmd BufNewFile,BufRead */getaround-analytics/dbt-bq/* set expandtab
autocmd BufNewFile,BufRead */getaround-analytics/dbt-bq/*.sql set foldlevel=0 foldmarker=(,) foldmethod=marker
autocmd BufNewFile,BufRead */getaround-analytics/dbt-bq/target/* set foldmethod=manual

source $HOME/.vim/config/dbt.vimrc
